---
- hosts: ec2-instance
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - jq        # Install jq for parsing JSON

    - name: Remove conflicting package
      apt:
        name: containerd.io
        state: absent
      ignore_errors: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # Configure AWS CLI (assuming credentials are pre-configured)
    - name: Configure AWS Region
      community.aws.aws_cli_configure:
        region: us-east-2

    # Login to ECR using AWS CLI and jq
    - name: Login to ECR
      command: >
        aws ecr get-login-password --region us-east-2 | 
        docker login --username AWS --password-stdin 339713096223.dkr.ecr.us-east-2.amazonaws.com
      register: ecr_login

    - name: Pull Docker image from ECR
      ansible.builtin.docker_image:
        name: 339713096223.dkr.ecr.us-east-2.amazonaws.com/personal-portfolio:latest
        source: pull

    - name: Run Docker container
      ansible.builtin.docker_container:
        name: portfolio_container
        image: 339713096223.dkr.ecr.us-east-2.amazonaws.com/personal-portfolio:latest
        ports:
          - "80:80"
        restart_policy: unless-stopped
        detach: yes
