---
- hosts: ec2-instance
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - git

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Clone project repository
      git:
        repo: 'https://github.com/RomanRadz/personal-portfolio.git'
        dest: /home/ubuntu/portfolio
        version: master
      become_user: ubuntu

    - name: Change directory to project
      ansible.builtin.file:
        path: /home/ubuntu/portfolio
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Build Docker image
      ansible.builtin.docker_image:
        name: portfolio_image
        build:
          path: /home/ubuntu/portfolio
        source: build

    - name: Run Docker container
      ansible.builtin.docker_container:
        name: portfolio_container
        image: portfolio_image
        ports:
          - "80:80"
        restart_policy: unless-stopped
        detach: yes
